### PR TITLE
Light fix

### PR DESCRIPTION
**Pull request by NoName824**
Changed external lights to the approximate position

### CODE REVIEW

**Review by xZreai — APPROVED** [review]
Definitely a improvement over what we had before, but we can finalize this once we have the full proper model ready

**Comment by Cryptic56** [comment]
Digital Flight Dynamics QA Report
PR Number: #15 
Discord Username: Cryptic4731
Date: 13/06/2021

Steps taken to test:

Edited CFG file
Spawned on runway
Observed exterior lights

issues (If any): N/A

Report: Pass

Media:
Capture
Capture
Capture

**Comment by tjugpal** [comment]
Digital Flight Dynamics QA Report
PR Number: (#15 )
Discord Username:V3ER#7412

Date:June 16th 2021

Steps taken to test: turned light switches on/off, spawned during the day and night

issues (If any): Nav lights float above the winglet and the beacon switch controls the nav lights. The position of the nav lights are too high on the winglet and need to be lower

Report:

Real aircraft
Screen-Shot-2017-11-15-at-3 24 08-PM

Sim
Screenshot_20
Screenshot_19
Screenshot_18

**Comment by NoName824** [comment]
Thanks for your feedback. I'm going to change it after the new wing with hopfully holes for the light +glas is there. At the moment it is only an approximate location

**Comment by Dynamic6448** [comment]
Looks good!

**Pull request merged**
