### PR TITLE
created captain sidestick in blender no texture hope this helps

### PR DESCRIPTION
**Pull request by airman50**
image

### CODE REVIEW

**Comment by Dynamic6448** [comment]
Can i see the topology?

**Comment by airman50** [comment]
> Can i see the topology?

image
image
image

**Comment by Dynamic6448** [comment]
Yep, as I thought, you didn't make it. Taken straight from the A20N. Also, models are only made by the development team, since the models are not open source.

**Comment by airman50** [comment]
> Yep, as I thought, you didn't make it. Taken straight from the A20N. Also, models are only made by the development team, since the models are not open source.

its not copied from the a320 used as a reference i made this myself

**Comment by Dynamic6448** [comment]
First of all, it's in triangles, and modeling is done in quads. Second, the topology is EXACTLY the same as the default A20N.

**Comment by airman50** [comment]
> > Yep, as I thought, you didn't make it. Taken straight from the A20N. Also, models are only made by the development team, since the models are not open source.
> 
> its not copied from the a320 used as a reference i made this myself

the msfs to blender importer is not that sophisticated and improvement to the joy stick i can make i spend a long time making this

**Comment by Dynamic6448** [comment]
Dude, just accept that this is not your work. I will once again ask you to stop.

**Comment by airman50** [comment]
> Dude, just accept that this is not your work. I will once again ask you to stop.

i am okay with you rejecting the model but all i was trying to do was help but now u accuse me of stealing someone else's work which is insulting as i spent my valuable time making it if you are so sure i stole it the i would like to see u prove it

**Comment by Dynamic6448** [comment]
The topology is proof enough, hence why I asked you to show it. I will now close this PR.

**Comment by HugoTro** [comment]
> > > Yep, as I thought, you didn't make it. Taken straight from the A20N. Also, models are only made by the development team, since the models are not open source.
> 
> > 
> 
> > its not copied from the a320 used as a reference i made this myself
> 
> 
> 
> the msfs to blender importer is not that sophisticated and improvement to the joy stick i can make i spend a long time making this 
> 
> 

Uhhh bro it is that good. The FBW one is close to completion, you can almost import a whole airframe and cockpit with it. Now Dynamic's choice was right

**Pull request closed without merging**
